### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by adicretu** [CTHRU/Hitrava#7]
**Describe the bug**
If I download the data from Huawei and rename it as HiZip.zip, I get this error:

C:\Users\cretua\WORK\Hitrava-3.2.5>python Hitrava.py --zip HiZip.zip --json_export
2020-04-17 12:46:14,301 - WARNING - extract_json - Could not find JSON file <data/Motion path detail data & description/motion path detail data.json> in ZIP file <HiZip.zip>.                                                             Nothing to convert.
Traceback (most recent call last):
  File "Hitrava.py", line 1746, in <module>
    main()
  File "Hitrava.py", line 1730, in main
    json_filename = HiZip.extract_json(args.zip, args.output_dir)
  File "Hitrava.py", line 1022, in extract_json
    raise Exception('Could not find file <data/motion path detail data.json> in ZIP file <%s>. \
Exception: ('Could not find file <data/motion path detail data.json> in ZIP file <%s>.                                     Nothing to convert.', 'HiZip.zip')

If I extract "motion path detail data.json" and I try to convert it I get this error:

PS C:\Users\cretua\WORK\Hitrava-3.2.5> python Hitrava.py --json '.\motion path detail data.json' --json_export
2020-04-17 12:50:40,404 - INFO - parse - Found one or more activities in JSON at index 0 to parse from 2018-09-02 (YYY-MM-DD)
2020-04-17 12:50:40,405 - INFO - parse - Exporting JSON data of activity at index 0 from 2018-09-02 to file ./output/HiTrack_20180902_135312.json
2020-04-17 12:50:40,407 - INFO - parse - Saving activity at index 0 from 2018-09-02 to HiTrack file ./output/HiTrack_20180902_135312 for parsing
2020-04-17 12:50:40,416 - INFO - parse - Parsing file <./output/HiTrack_20180902_135312>
2020-04-17 12:50:40,428 - ERROR - parse - Error parsing JSON file <.\motion path detail data.json>
'wearSportData'
Traceback (most recent call last):
  File "Hitrava.py", line 1185, in parse
    if 'swim_pool_length' in activity_detail_dict['wearSportData']:
KeyError: 'wearSportData'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Hitrava.py", line 1746, in <module>
    main()
  File "Hitrava.py", line 1736, in main
    hi_activity_list = hi_json.parse(args.from_date)
  File "Hitrava.py", line 1198, in parse
    raise Exception('Error parsing JSON file <%s>', self.json_file.name)
Exception: ('Error parsing JSON file <%s>', '.\\motion path detail data.json')

**Comment by CTHRU** [comment]
@adicretu Thanks for creating the ticket. If you want, you can remove the link to your HiZip.zip file. I will check later what's going on using a temporary local copy. I will delete my local copy once the issue is resolved.

At a first glance, the ZIP file and your command look OK. I get back to you soon.

**Comment by CTHRU** [comment]
@adicretu I'm making progress in solving the issue you reported. Huawei must have recently changed the folder structure in the ZIP file. The next version will support both the 'old' and 'new' ZIP folder structure.

I would require some more information about the activity in the second part of your ticket (from Sep 2nd, 2018). The activity type is currently unknown to Hitrava and the data structure is different from the known types. I would like to support it.  Could you take a look in the Huawei Health app and let me know what the activity type is, e.g. 'indoor run' -> I suspect an indoor activity (registered without a fitness device?). Thank you for providing me the info.

**Comment by CTHRU** [comment]
@adicretu  I just released a new version that should solve your main issues (except the activity from Sep 2nd, 2018, see above). Don't hesitate to let me know if you still experience problems.

I will leave the ticket open for now for your feedback and the info on the activity from Sep 2nd, 2018.

**Comment by adicretu** [comment]
Hi Christoph. Thanks a lot for the time dedicated to this script. It help us here and we appreciate it.
The activity from 2018-09-02 is indeed an indoor run (treadmill) recorded manually.
Cheers!
