### ISSUE TITLE
[BUG] - INFO - main error

### ISSUE THREAD

**Issue by csteri** [CTHRU/Hitrava#73]
**Use:**
Hitrava: 5.1.1
Python: 3.11.3
Windows 11 x64

I changed the Run_Hitrava_Decrypt.cmd file from:
`Hitrava.py --zip HiZip.zip --password 123456 --json_export
pause`
to:
`python Hitrava.py --zip HiZip.zip --password aaa123 --json_export
pause`

 After run in **Logs terminal:**
```
C:\Users\name\Desktop\Hitrava-5.1.1>python Hitrava.py --zip HiZip.zip --password aaa123 --json_export
2023-05-21 09:48:13,870 - INFO - main - Hitrava version 5.1.1 (build 2207.2501) started with arguments ['--zip', 'HiZip.zip', '--password', 'aaa123', '--json_export']
2023-05-21 09:48:13,870 - INFO - main - Running on Python version 3.11.3
Traceback (most recent call last):
  File "C:\Users\name\Desktop\Hitrava-5.1.1\Hitrava.py", line 2165, in <module>
    main()
  File "C:\Users\name\Desktop\Hitrava-5.1.1\Hitrava.py", line 2145, in main
    json_filename = HiZip.extract_json(args.zip, args.output_dir, args.password)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\name\Desktop\Hitrava-5.1.1\Hitrava.py", line 1158, in extract_json
    completed_process = subprocess.run(unzip_cmd,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\name\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\name\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\name\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

C:\Users\name\Desktop\Hitrava-5.1.1>pause
Press any key to continue . . .
```

**Comment by csteri** [comment]
I solved the problem, I was missing 7za.exe from root folder
